CONFIG_ZMK_POINTING=y

CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=400
CONFIG_PMW3610_CPI_DIVIDOR=1
CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_PMW3610_SCROLL_TICK=16
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_SCROLL_X=y
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_POLLING_RATE_125_SW=y

# Input Processor版しきい値付きAMLを使う
CONFIG_ZMK_INPUT_PROCESSOR_TEMP_LAYER_THRESHOLD=y

# PMW3610ドライバ側AMLは使わない
# CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700
# CONFIG_PMW3610_MOVEMENT_THRESHOLD=0

CONFIG_PMW3610_SMART_ALGORITHM=y
